server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account_db
    username: root
    password: "123456"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: account-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#    enabled: false