server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**

        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**

        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/items/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka