package org.ChenChenChen99.itemservice.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.util.List;
import java.util.UUID;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Document(collection = "items")
public class Item {

    @Id
    private String id; // Automatically generated by mongodb
    private String name;
    private double price;
    private String upc;
    private List<String> imageUrls;
    private Inventory inventory;

    @Data
    @AllArgsConstructor
    @NoArgsConstructor
    @Builder
    public static class Inventory {
        private int available;
        private int reserved;
    }
}