server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: root
    password: "123456"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service
      properties:
        spring.json.trusted.packages: "*"

  application:
    name: payment-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    # enabled: false