server:
  port: 8082

spring:
  application:
    name: item-service

  data:
    mongodb:
      uri: mongodb://root:123456@localhost:27017/itemdb?authSource=admin

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: item-service
      properties:
        spring.json.trusted.packages: "*"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    # enabled: false